### PR TITLE
Synchronize scripts with Vulkan / OpenXR

### PR DESCRIPTION
**Pull request by oddhack**
No meaningful effect on generated files (non-semantic sorting of rewrite rules, and insertion of some whitespace in HTML tags).

@bashbaug I recommend accepting soon. This doesn't affect generated specs or refpages.

### CODE REVIEW

**Comment by bashbaug** [comment]
I'm seeing a few warnings when I build the specs after these changes:

```sh
scripts/gencl.py    -registry xml/cl.xml -o /home/bashbaug/git/OpenCL_API/generated/api apiinc
WARNING: Attempt to redefine cl_half (this should not happen)
WARNING: Attempt to redefine cl_d3d11_device_source_khr (this should not happen)
WARNING: Attempt to redefine cl_d3d11_device_set_khr (this should not happen)
WARNING: Attempt to redefine cl_device_partition_property_ext (this should not happen)
WARNING: Attempt to redefine cl_kernel_sub_group_info (this should not happen)
WARNING: Attempt to redefine cl_dx9_surface_info_khr (this should not happen)
WARNING: Attempt to redefine ('CL_VERSION_1_2', 'opencl') (this should not happen)
```

The specs still seemed to generate correctly but I'd still like to see them fixed.  I suspect this is an issue in the XML file but I haven't looked further.  If these changes are time critical, no worries, we can fix these warnings shortly afterwards with a separate PR.

There is a merge conflict now that will need to be resolved.  Thanks!

**Comment by oddhack** [comment]
Wow, I'm not sure what happened there. Definitely some XML problems; perhaps I started from a different branch than master. I will address this shortly, thanks.

**Comment by oddhack** [comment]
@bashbaug this should be OK now. Specs generate without XML-related warnings - those were turned up by the script changes - and I also fixed a longstanding issue where part of the OpenCL 2.0 API had been mislabelled as part of OpenCL 1.2. Generated spec HTML is identical to master aside from the date / commit IDs imbedded in the headers. I will go ahead and merge this shortly.

**Comment by oddhack** [comment]
Well, actually I will leave it up to you to merge since that's a bit outside my scope, but hopefully it can go in today.

**Comment by bashbaug** [comment]
Thanks - I've verified that everything builds and works fine with these changes.  Rebased and pushed to master with 1c6a44ff9f44c745fc98fc3de8ccb05155ce8741.

I'll open a separate issue regarding header generation from the XML file.  Seems like this is a nice capability to have, and it'd help to surface any additional XML issues.

**Pull request closed without merging**
