### PR TITLE
add specific memory and semaphore enums for CL_DEVICE_HANDLE_LIST_KHR

### PR DESCRIPTION
**Pull request by bashbaug**
see #864 

Instead of reusing the same `CL_DEVICE_HANDLE_LIST_KHR`, adds a memory-specific `CL_MEM_DEVICE_HANDLE_LIST_KHR`, and a semaphore-specific `CL_SEMAPHORE_DEVICE_HANDLE_LIST_KHR`.

Reuses the same value for `CL_MEM_DEVICE_HANDLE_LIST_KHR` as discussed.  The enum value for `CL_SEMAPHORE_DEVICE_HANDLE_LIST_KHR` is new, though.

### CODE REVIEW

**Comment by bashbaug** [comment]
Discussed in the August 1st teleconference:
- Remove the symbol name completely.  Note that this will require rephrasing a few places that currently use the asciidoc dictionary entry.
- We will leave open another week or so for review.

**Comment by bashbaug** [comment]
I've made the changes to remove `CL_DEVICE_HANDLE_LIST_KHR` completely, as we discussed.

**Comment by bcalidas** [comment]
Looks ok

**Review by nikhiljnv — APPROVED** [review]
LGTM.

**Comment by nikhiljnv** [comment]
Merging as discussed on Aug 22 subgroup call.

**Pull request merged**
