### PR TITLE
Minor formatting fixes for cl_khr_fp64

### PR DESCRIPTION
**Pull request by StuartDBrady**
Add a missing line break and fix a stray ` in the markup.

### CODE REVIEW

**Review by bashbaug — APPROVED** [review]
Thanks!  Merging immediately since these are obvious fixes.

**Comment by bashbaug** [comment]
@outofcontrol can you please check on the CLA status for this PR?  It seems stuck and I know Stuart has committed to this repository before.  Thanks!

**Comment by Khronoswebmaster** [comment]
CLA Assistant seems a bit slow today. I see this has no gone through. Let me know if I can do more to help.

**Review by alycm — APPROVED** [review]
LGTM, CLA issue seems unstuck, merging.

**Pull request merged**
