### PR TITLE
Add missing cl_arm_job_slot_selection extension to XML

### PR DESCRIPTION
**Pull request by kpet**
Change-Id: I8267f927449c0d884f82c7952b9cee99b50d1b19

### CODE REVIEW

**Review by bashbaug — APPROVED** [review]
LGTM, matches the headers.

**Comment by bashbaug** [comment]
This needs a trivial rebase now.

**Comment by kpet** [comment]
@bashbaug Now rebased

**Review by alycm — APPROVED** [review]
LGTM.  This is a second review, will merge.

**Pull request merged**
