### PR TITLE
update non-provisional extensions to version 1.0.0

### PR DESCRIPTION
**Pull request by bashbaug**
Updates extensions that have been finalized to version 1.0.0.

### CODE REVIEW

**Comment by bashbaug** [comment]
@oddhack, there are a few extension specs with a comment block like this one:

```
//@ *Revision*::
//@     1.0.0
//@ *Extension and Version Dependencies*::
//@     This extension requires OpenCL 3.0.
```

Is this used for anything, or can it be removed?

**Comment by oddhack** [comment]
> @oddhack, there are a few extension specs with a comment block like this one:
> 
> ```
> //@ *Revision*::
> //@     1.0.0
> //@ *Extension and Version Dependencies*::
> //@     This extension requires OpenCL 3.0.
> ```
> 
> Is this used for anything, or can it be removed?

Those are just left over from the conversion process and can safely be removed. The dependencies are being generated from the XML now.

**Review by alycm — APPROVED** [review]
LGTM.

**Comment by alycm** [comment]
CLA bot hasn't run, already documented in https://github.com/KhronosGroup/OpenCL-Docs/issues/1128, there are no CLA issues with this PR, merging.

**Pull request merged**
