### PR TITLE
Add Subgroup to the list of valid Memory Scopes for 2.1/2.2

### PR DESCRIPTION
**Pull request by kpet**
Signed-off-by: Kevin Petit <kevin.petit@arm.com>

### CODE REVIEW

**Comment by bashbaug** [comment]
I think there is an issue here, but I wonder if this is the wrong fix.

For OpenCL 2.1 or newer, or any implementation supporting subgroups, couldn't **Subgroup** be a valid _Scope_ for _Memory_?  It would correspond to an atomic with `memory_scope_sub_group`.

**Comment by kpet** [comment]
Agree this is missing. I was planning to deal with all the subgroup-related issues later but this was probably a bad idea :). I'll repurpose this PR to add the missing _Subgroup_ _Scope_ and look into reorganising the rules and solving the other issues later instead.

**Comment by bashbaug** [comment]
> look into reorganising the rules and solving the other issues later instead.

Heads up, I'm already about halfway through refactoring these parts of the environment spec already, for other reasons (see internal issue 156).  I appreciate the help, but let's be sure we aren't duplicating work - thanks!

**Comment by kpet** [comment]
Right, hadn't caught up with it yet. I will pause work on the environment spec until you're done with that. Do you want to get this in or would you rather I close it?

**Comment by kpet** [comment]
This will be addressed by @bashbaug 's #84. Closing.

**Pull request closed without merging**
