### PR TITLE
Fix description of the half precision math functions

### PR DESCRIPTION
**Pull request by Melirius**
Likewise in already merged https://github.com/KhronosGroup/SYCL-Docs/pull/306

### CODE REVIEW

**Comment by bashbaug** [comment]
LGTM, but I think we need to update the OpenCL C spec as well:
https://github.com/KhronosGroup/OpenCL-Docs/blob/a897dfb2e238e7e0b623dd9b774e67a922fe52dc/OpenCL_C.txt#L4928

I did a quick check through the SPIR-V environment spec and I didn't see anything similar, so I think it's OK, but it'd be nice to have a second pair of eyes to be sure I didn't miss it.  Thanks!

**Comment by Melirius** [comment]
Updated the OpenCL C spec.

**Review by bashbaug — APPROVED** [review]
Thank you for the fixes!

**Comment by bashbaug** [comment]
Merging, fixes make sense and this will align the OpenCL and SYCL specs.

**Pull request merged**
