### PR TITLE
Update copyright dates to 2019.

### PR DESCRIPTION
**Pull request by oddhack**

### CODE REVIEW

**Comment by oddhack** [comment]
@outofcontrol this is claiming I haven't signed the CLA, although when I click through to the CLA page, it claims I *have* signed it. No idea what's up here (especially since I've submitted many MRs to other KhronosGroup projects without running into this). Maybe the CLA server is wonky? Please check into this.

**Comment by outofcontrol** [comment]
Did you commit with a different email address by any chance? The note is suggesting that 'Jon Leech' is not a Github use:

"Jon Leech seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account."

**Comment by oddhack** [comment]
@outofcontrol possibly the CLA-Assistant was briefly confused by something? It seems to be cleared up now. The instructions they give for finding the email address you committed with don't actually work so I don't know what it thinks was wrong specifically, but I made sure my .gitconfig email setting was added to my Github account settings - though this has not been an issue previously.

**Comment by outofcontrol** [comment]
There has been one or two instances where the CLA site is a bit slow on sorting out the signing of a CLA. Something to keep a lookout for.

**Pull request merged**
