### PR TITLE
Drop "future" status of generic addrspace qualifier

### PR DESCRIPTION
**Pull request by svenvh**

### CODE REVIEW

**Review by kpet — APPROVED** [review]
LGTM

**Review by alycm — COMMENTED** [review]
By dropping the "future" status this is effectively adding a new pair of keywords.  This was discussed before, the outcome was summarised in https://github.com/KhronosGroup/OpenCL-Docs/issues/501.  A possible outcome there was to add this keyword in a future version.

Maybe I'm not understanding the intent of this change though, as this PR doesn't actually define a meaning for the keywords.

I'm aware that Clang already supports these keywords, and treats then the same as the unnamed generic address space.

**Review by bashbaug — CHANGES_REQUESTED** [review]
This seems a little premature given the discussion in #501.

Additionally, do we have any CTS tests that explicitly use `generic` as an address space qualifier?

**Comment by svenvh** [comment]
Apologies, I wasn't aware of #501 and thought this was simply an oversight, driven by the observation that Clang has been supporting the `generic` qualifiers since 2014(!)  There are no CTS tests that use `generic` as an address space qualifier yet.

**Comment by AnastasiaStulova** [comment]
Just one small clarification here:

> I'm aware that Clang already supports these keywords, and treats them the same as the unnamed generic address space.
Generic address space is implemented and specified as a named address space. However, spec incorrectly _pretends_ that it is an unnamed address space adding lots of confusion.

So it would be good if we could correct this issue at some point.

**Pull request closed without merging**
