### PR TITLE
Add cl_arm_protected_memory_allocation specification

### PR DESCRIPTION
**Pull request by kpet**
Signed-off-by: Kevin Petit <kevin.petit@arm.com>
Change-Id: I969d5c64fdf167e6453fc545e85b46cb5663d1c5

### CODE REVIEW

**Review by bashbaug — COMMENTED** [review]
Spec source looks straightforward.  Should there be a section for this extension at the end of the XML file?  Right now the new bit is unassigned to any extension so things like the extension header generation scripts won't pick it up.

**Comment by kpet** [comment]
> Should there be a section for this extension at the end of the XML file?

Yes, there should be one. I've added it. We should have checks in the CI for this. I'll follow up on it.

**Review by bashbaug — APPROVED** [review]
Thanks, latest changes LGTM.

**Review by alycm — APPROVED** [review]
LGTM.  This is the second review and this has been up a while, I'll merge.

**Pull request merged**
