### PR TITLE
cl_img_mem_properties: Memory hint flags update

### PR DESCRIPTION
**Pull request by jebasamuelimg**
Added new memory allocation hint flags to specify underlying physical allocation preference.

### CODE REVIEW

**Review by bashbaug — APPROVED** [review]
LGTM.  It doesn't need to hold up this PR but you may want to update the extension spec as well:

https://github.com/KhronosGroup/OpenCL-Docs/blob/main/extensions/cl_img_mem_properties.asciidoc

**Comment by SunSerega** [comment]
Shouldn't `cl_device_feature_capabilities_img` also be in a `<require>` tag?

**Comment by jebasamuelimg** [comment]
> LGTM. It doesn't need to hold up this PR but you may want to update the extension spec as well:
> 
> https://github.com/KhronosGroup/OpenCL-Docs/blob/main/extensions/cl_img_mem_properties.asciidoc

Thank you Ben. Yes. I will do it in separate PR.

**Comment by jebasamuelimg** [comment]
@bashbaug Could you help me to merge the PR request? I don't have write access permission to merge it.

Thank you

**Pull request merged**
