### PR TITLE
add definition of Valid Object to glossary

### LINKED ISSUE #482: What is the definition of a "valid event"
The phrase "...valid events" is used in every API that accepts an event waitlist, but there is no definition of what a valid event is.

I think a valid event is any event that can be queried by clGetEventInfo - returned by an OpenCL API, is associated with an active context (if applicable), and has not been destroyed (if applicable).

### PR DESCRIPTION
**Pull request by bashbaug**
Adds the definition of a "valid object" to the glossary, with the text described in this comment:

https://github.com/KhronosGroup/OpenCL-Docs/issues/482#issuecomment-795685410

### CODE REVIEW

**Review by jlewis-austin — COMMENTED** [review]
This looks good, but I can't find a separate issue to clarify the implementation responsibility to check NULL only, with the other conditions implementation-defined. 

I'm wondering if we need to tackle those changes along with this? Otherwise, removing the ambiguity about what valid means also implies specific requirements on error checking for errors defined in terms of _valid events_, e.g.
> [CL_INVALID_EVENT_WAIT_LIST](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_INVALID_EVENT_WAIT_LIST) if event_wait_list is NULL and num_events_in_wait_list > 0, or event_wait_list is not NULL and num_events_in_wait_list is 0, or if event objects in event_wait_list are not valid events.

**Comment by bashbaug** [comment]
Hmm, good point, I've taken off the "fixes" comment so merging this PR will not close the issue until this is resolved.

I can add another sentence to the glossary definition if we think this is sufficient, something like:

> Implementations are only required to check for a `NULL` object to test if an object is valid; the behavior for all other invalid objects is implementation-defined.

Or, if we think that more word-smithing is required, we can take the discussion back to the issue.

I do think this addition is useful even if there is still work to be done to define which invalid objects an implementation needs to test for.

**Comment by jlewis-austin** [comment]
@bashbaug I like your idea to add the implementation requirements in the glossary. If discoverability ends up being an issue, it would be nice if we could link usages of "_valid \<objects\>_" to the glossary description--I'm not sure how feasible that is to do, though.

**Review by jlewis-austin — APPROVED** [review]
LGTM

**Review by alycm — APPROVED** [review]
LGTM.

**Pull request merged**
